### ISSUE TITLE
Theme stopped updating

### ISSUE THREAD

**Issue by brunolemos** [styled-components/styled-components#261]
## Version
1.1.2 on React Native

## Expected Behavior
All components that use { theme } update when the theme is changed.

## Actual Behavior
Most of components stopped updating the colors after migrating from v1.1.1 to v1.1.2.

**Comment by mxstbr** [comment]
That must be #253? @michalkvasnicak

**Comment by michalkvasnicak** [comment]
@mxstbr yeah it is but I am not using react-native so I don't know how to test it. 

Only difference between `StyledComponent` and `StyledNativeComponent` is this line https://github.com/styled-components/styled-components/blob/master/src/models/StyledNativeComponent.js#L31. I forgot to set this to `null`.

@brunolemos Are you changing `theme` using the `ThemeProvider`?

**Comment by michalkvasnicak** [comment]
Ok I will try.

**Comment by michalkvasnicak** [comment]
@mxstbr I couldn't get this worked. `npm run ios` is failing with this output.

```
Found Xcode project native.xcodeproj
Launching iPhone 6 (iOS 10.1)...
Building using "xcodebuild -project native.xcodeproj -scheme native -destination id=ACA806AE-5F06-45B7-ABB1-51D0E52A3F70 -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/Michal/Work/styled-components/example/native/ios/build


=== BUILD TARGET native OF PROJECT native WITH CONFIGURATION Debug ===


Check dependencies



CompileC build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/Objects-normal/x86_64/AppDelegate.o native/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Michal/Work/styled-components/example/native/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/Michal/.nvm/versions/node/v6.9.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/Michal/Work/styled-components/example/native/node_modules/.bin:/Users/Michal/.nvm/versions/node/v6.9.1/bin:/usr/local/opt/php56/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/usr/local/MacGPG2/bin:/usr/local/opt/go/libexec/bin:/Users/Michal/Work/Go/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/Michal/Work/styled-components/example/native/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/Michal/Work/styled-components/example/native/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=8.0 -g -Wno-sign-conversion -Wno-infinite-recursion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/native-generated-files.hmap -I/Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/native-own-target-headers.hmap -I/Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/native-all-target-headers.hmap -iquote /Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/native-project-headers.hmap -I/Users/Michal/Work/styled-components/example/native/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/Michal/Work/styled-components/example/native/ios/../node_modules/react-native/React -I/Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/DerivedSources/x86_64 -I/Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/DerivedSources -F/Users/Michal/Work/styled-components/example/native/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/Objects-normal/x86_64/AppDelegate.d --serialize-diagnostics /Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/Objects-normal/x86_64/AppDelegate.dia -c /Users/Michal/Work/styled-components/example/native/ios/native/AppDelegate.m -o /Users/Michal/Work/styled-components/example/native/ios/build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/Objects-normal/x86_64/AppDelegate.o

/Users/Michal/Work/styled-components/example/native/ios/native/AppDelegate.m:12:9: fatal error: 'RCTBundleURLProvider.h' file not found
#import "RCTBundleURLProvider.h"
        ^
1 error generated.



** BUILD FAILED **



The following build commands failed:
        CompileC build/Build/Intermediates/native.build/Debug-iphonesimulator/native.build/Objects-normal/x86_64/AppDelegate.o native/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/native.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/native.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

**Comment by gitadept** [comment]
Have the same behavior with React after upgrade from 1.0.3 version. Don't know, maybe I'm doing something wrong, but think it is important. I've tried previous versions before #253, themes work with #252 bug, but work.

**Comment by k15a** [comment]
Hey, that's not just a problem with React Native. It's not working with React as well.

**Comment by mxstbr** [comment]
> It's not working with React as well.

@michalkvasnicak can you reproduce that?

**Comment by michalkvasnicak** [comment]
@mxstbr I will take a look. With react-native I have problem, I can't to get build working (see above).

**Comment by michalkvasnicak** [comment]
@mxstbr Ok I can reproduce that in test case ( current test cases are not enough because they test generated css but don't check if `className` is correct ).

**Comment by michalkvasnicak** [comment]
Could someone try #262  (react and react-native too)?
