### ISSUE TITLE
Jest Tests Fail to Run when Upgrading to V3 of Styled Components (React Native)

### ISSUE THREAD

**Issue by Daadler6** [styled-components/styled-components#1451]
## Version
styled-components: 3.0.2

## Reproduction

First, just want to say thank you for this amazing lib. Of all the packages I have used over the years this one is my favorite. I am in the process of upgrading from V2 -> V3 (React Native Application). I bumped the package, npm installed, and changed all references from ```styled-components/native``` to ```styled-components```. The app works fine but my jest tests are now failing with the following issues (Depending on the test being ran)

I've also opened a Spectrum thread here: https://spectrum.chat/styled-components/help?thread=b3b5504b-b01e-4a6a-8cee-b4c0a824c13b

```
Test suite failed to run:
TypeError: _styledComponents2.default.Text is not a function
TypeError: _styledComponents2.default.View is not a function
TypeError: _styledComponents2.default.Image is not a function
```

## Steps to reproduce

1. Bump Package to 3.0.2
2. npm install
3. Replace all deprecated styled-components/native instances
4. Run JEST test suite

## Expected Behavior

Jest tests should be able to run

## Actual Behavior

Tests are failing

## Example Unit Test

Below is an example of a UT I am running. It might help pinpoint the issue

```
import { SelectedCustomer } from '../../../src/shared-components';
import themeUtil from '../../testUtils/themeUtil';

describe('<SelectedCustomer />', () => {
  const routeToCustomers = jest.fn();
  beforeEach(() => {
    util = themeUtil(SelectedCustomer);
  });

  it('renders a SelectedCustomer with default props', () => {
    const tree = util.renderWithTheme();
    expect(tree).toMatchSnapshot();
  });

  it('renders a SelectedCustomer with default props', () => {
    const newProps = { routeToCustomers };
    const wrapper = util.shallow(newProps);
    expect(wrapper.find('#route-link').length).toEqual(1);
    wrapper.find('#route-link').simulate('press');
    expect(routeToCustomers.mock.calls.length).toBe(1);
    expect(wrapper).toMatchSnapshot();
  });
});
```

**Comment by philpl** [comment]
> Replace all deprecated styled-components/native instances

It seems that Jest is not resolving the correct extensions for your React Native test code.

Have you tried setting up the `moduleFileExtensions`? https://facebook.github.io/jest/docs/en/configuration.html#modulefileextensions-array-string

**Comment by Daadler6** [comment]
@philpl - My current jest config looks like so:

```  
 "jest": {
    "preset": "jest-expo",
    "setupFiles": [
      "<rootDir>/jestConfig.js"
    ],
    "moduleFileExtensions": ["js", "json", "jsx", "node"],
    "testPathIgnorePatterns": [
      "<rootDir>/__tests__/screens/customers",
      "<rootDir>/__tests__/testUtils",
      "<rootDir>/node_modules"
    ],
    "timers": "fake",
    "transformIgnorePatterns": []
  }```

**Comment by vvasilev-** [comment]
The `moduleNameMapper` option can be used as a temporary workaround. 😄 

```
'moduleNameMapper': {
    'styled-components': '<rootDir>/node_modules/styled-components/dist/styled-components.native.cjs.js'
  }
```

**Comment by machour** [comment]
Nice workaround @vvasilev-, I can confirm it's working 🎉

**Comment by nyl9488** [comment]
Hi... it is not working ... i am using v4

**Comment by tpucci** [comment]
ℹ️ _Version info:_ `"styled-components": "4.1.3"`

I faced this issue and have been able to solve it using the following jest config:

```js
// jest.config.js

module.exports = {
  ...
  moduleNameMapper: {
    ...
    '^styled-components$':
      '<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js',
  },
  ...
};
```

**Comment by EugeneDraitsev** [comment]
@nyl9488 @tpucci 
in styled-components v4 you should replace all 
```
import styled from 'styled-components'
```

with 
```
import styled from 'styled-components/native'
```

and remove moduleNameMapper for styled-components and it will work.

**Comment by AurangzaibRamzan** [comment]
for styled-component V4 you will use the
 `"moduleNameMapper": {
      "styled-components": "<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js"
    },`

They just shifted native to separate folder

**Comment by joseph-d-p** [comment]
@AurangzaibRamzan as pointed out by @EugeneDraitsev in [his comment](https://github.com/styled-components/styled-components/issues/1451#issuecomment-457567315), you don't need the `moduleNameMapper`.

**Comment by GiladR1979** [comment]
Reviving this for the styled-components v5, the correct moduleNameMapper value now is:

`"moduleNameMapper": {
    "styled-components": "<rootDir>/node_modules/styled-components/native/dist/styled-components.native.cjs.js"
  }
}`
