### ISSUE TITLE
styled.source fails on typescript after upgrading to 6.3.X

### ISSUE THREAD

**Issue by rigobauer** [styled-components/styled-components#5651]
After upgrading to 6.3.8, when I check the types it fails because styled.source`` :

```
Type error: Property 'source' does not exist on type '(<Target extends WebTarget, InjectedProps extends object = BaseObject>(tag: Target) => Styled<"web", Target, Target extends KnownTarget ? ComponentPropsWithRef<Target> & InjectedProps : InjectedProps, BaseObject>) & { ...; }'.
```

(works correctly on 6.2.0)

**Comment by ALI-KHALED-13** [comment]
I think some interfaces been removed indeed like KnownTarget

**Comment by rigobauer** [comment]
Yeah, I know it's not a visual element, but it breaks if you were using it for `.attrs` or similar. But if it's intentional, I guess it's ok (there are workarounds)... I'll close this
