### ISSUE TITLE
Homepage webpackbin link is out of date

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#580]
https://www.webpackbin.com/V1VNoINA- gives an error.

**Comment by geelen** [comment]
On styled-components.com I mean.

**Comment by siddharthkp** [comment]
The styled-components [boilerplate on webpackbin.com](https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN) seems broken too 😢  (uses 2.0.0-7)


`Uncaught TypeError: _styledComponents2.default.h1 is not a function`

works with 2.0.0-6

**Comment by MMayla** [comment]
It's working now with `v2.0.0-10` but the URLs in the README needs to be updated.

**Comment by jdhines** [comment]
@MMayla How did you get webpackbin to work with this version? I put it into the config, but then it threw this error: `Uncaught TypeError: Super expression must either be null or a function, not undefined`

**Comment by mxstbr** [comment]
Fixing now, sorry for the delay!

**Comment by mxstbr** [comment]
Also getting "Uncaught TypeError: Super expression must either be null or a function, not undefined", what the fuck is going on there? /cc @christianalfoni why did all of our bins suddenly break?

**Comment by christianalfoni** [comment]
@mxstbr I am not sure what is happening, I believe it is the sandbox that is not building correctly. I did just update to later version of webpack, which might be reason. But I am in loss of time due to work and family. Holidays coming up though, so will go through current issues.

Would be great if you could try to delete cookies though, just to see if that helps. That would confirm that it is the sandbox itself and not the bundles at least.

Sorry about it, but yeah... it is just very hard to test these changes.

It is working on my end btw. Though not sure if it is the bundle or the sandbox. A deletion of cookies will verify that :)

**Comment by k15a** [comment]
I've had the same problem and it's working for me after deleting cookies.

**Comment by mxstbr** [comment]
Damn, so it's the sandbox. Can we hotfix that from our side somehow so people don't get a horrible first experience of styled-components?

**Comment by christianalfoni** [comment]
It is rather hard to track down why. The cookies expire rather quickly, it
might be related to that. Away with family this weekend, but I will find
some time later. Now we know it is related to the sandbox and likely the
expiration of your cookie... as it works fine with a fresh cookie :-)

**Comment by christianalfoni** [comment]
Okay, I believe the issue is fixed now. It was related to the latest fix where it made it possible to import `some-lib/whatever/index.js` as `some-lib/whatever`... this is normal behaviour in Webpack, but due to using DLL bundles something awful happened there.

I kept the scope of this fix within the package itself, not its dependencies (which you would never require this way anyways), fixing the issue and keeping the functionality.

The reason this was not discovered (cause I always go through all boilerplates) is that I did not notice that the build failed on the EU instance on Heroku, so everything worked fine as I am using the instance.

Really sorry about this, I need to figure out a way to automate this testing :)

**Comment by mxstbr** [comment]
Everything works again! :tada:

Thank you so much for digging in @christianalfoni, much much appreciated :heart: Enjoy the time with your family!

**Comment by MMayla** [comment]
@mxstbr They are not working with me.
I have this error with [this](https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN): 
```
Uncaught TypeError: Super expression must either be null or a function, not undefined
```
and this error with [this](https://www.webpackbin.com/bins/-Kee_EvBIQAeG2pySjbH):
```
Uncaught TypeError: _styledComponents2.default.input is not a function
```

**Comment by k15a** [comment]
Can confirm that the second one isn't working for me as well. Looks like updating the styled-components version will fix it.

**Comment by christianalfoni** [comment]
@MMayla @k15a Hi guys... this seem very strange. Both of them are working fine on my end. The bundling of the DLL with the Bin happens the same way for everyone and there is no cache on that. So the first bin should instantly have worked for everyone. Could you please confirm that there is still an issue?

About the second error that seems related to a previous issue where a DLL bundling bug was introduced. Webpackbin is extremely vulnerable to these bugs due to its aggressive caching. But this has been resolved, but your browser might still have cached the DLL. Would be great if you could verify the cache is also cleared, or just update config to later version as that will produce a new DLL bundle  :)

 I have to dig deeper if there is still an issue here, really appreciate you reporting and giving examples here!

**Comment by k15a** [comment]
Both are working for me in chromes incognito today so it should be related to something cached.

**Comment by christianalfoni** [comment]
@k15a Thanks for confirming @k15a! :)

**Comment by MMayla** [comment]
Working for me after cleaning cache. Thanks guys :)
