### ISSUE TITLE
Problem with build with webpack2.1.0-beta

### ISSUE THREAD

**Issue by mayacode** [styled-components/styled-components#157]
It could be also webpack related issue, just wanted to make you aware about the problem

## Version
1.0.10

## Reproduction
in webpackbin it works - http://www.webpackbin.com/4yqYB5WlM but I'm not able to choose version of webpack

## Steps to reproduce
git clone https://github.com/mayacode/react-redux-starter/tree/styled-components-problem
`npm install`
`webpack`

I have `webpack@^2.1.0-beta.25` and `webpack-dev-serve@^2.1.0-beta.10` installed globally.

## Expected Behavior
`const Title = styled.h1` should work

## Actual Behavior
open index.html
in console you'll see `Uncaught TypeError: _styledComponents2.default.h1 is not a function(…)`

but if you change `const Title = styled.h1` to `const Title = styled.default.h1` everything works

**Comment by mxstbr** [comment]
Awesome, thanks for the reproduction to #115! I'll check this out asap!

**Comment by mxstbr** [comment]
This is actually a problem with your setup. You're telling both Babel and webpack to transpile ES2015 modules, which is why you end up with `.default.default`. /cc @TheLarkinn, maybe he has an idea how to avoid this?

The fix is to disable babel's modules transpiling in your `webpack.config.js`:

```
      {
        loader: 'babel',
        query: {
          presets: [['es2015', { modules: false }], 'react', 'stage-0']
        }
      }
```

(notice the `modules: false`)

![screen shot 2016-11-01 at 16 49 12](https://cloud.githubusercontent.com/assets/7525670/19896000/22dfec12-a053-11e6-87d7-c4feb995d459.png)

**Comment by mayacode** [comment]
Thank you, a lot!!

**Comment by rohmanhm** [comment]
Got same issue.
Can you help me, I had different settings in my `webpack.config.js` file.

```
const isDev = process.env.NODE_ENV != 'production';
const webpack = require('webpack');
const path = require('path');

module.exports = {
	entry: path.join(__dirname, 'src/app.js'),
	output: {
		path: path.join(__dirname, 'src/assets/js'),
    publicPath: '/assets/js',
		filename: 'bundle.js'
	},
  devtool: isDev ? 'inline-sourcemap' : false,
	resolve: {
		extensions: ['.js', '.jsx']
	},
  plugins: isDev ? [] : [
    // some plugin to optimize
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({mangle: false, sourcemap: false})
  ],
	module: {
		rules: [
      {
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['es2015', 'react', 'stage-0']
          }
        },
        resource: {
          exclude: /(node_modules|bower_components)/,
          test: /.jsx?$/
        }
      }
      
    ]
	}
}
```

**Comment by k15a** [comment]
@rohmanhm do you have a babel.rc?

**Comment by rohmanhm** [comment]
@k15a After changing my config still didn't work. I'm using new configuration recommendation by webpack 2

**Comment by k15a** [comment]
Do you have a `.babelrc` file? If yes set `babelrc` to `false` in your `webpack.config.js` in the `babel-loader` options.

**Comment by rohmanhm** [comment]
removed `.babelrc` file, 
and used this config
```
options: {
  presets: [['es2015', { modules: false }], 'react', 'stage-0']
}
```
Work perfectly without an `alias` to `styled-components`
Thanks!!
