### ISSUE TITLE
v3.4.7 - warnInjectGlobalDeprecated is not a function

### ISSUE THREAD

**Issue by BenMagyar** [styled-components/styled-components#2014]
## Environment
```
 - styled-components: ^3.4.4 => 3.4.7
```

## Reproduction
In 3.4.7 a deprecation warning for `injectGlobal` was introduced that throws a `TypeError` in production mode. Running a build in with `NODE_ENV=production` that uses `injectGlobal` causes the build to fail. 

This is caused by #2000 here: 
https://github.com/styled-components/styled-components/pull/2000/files#diff-095484d1d0538c1c11e49a50c9475a20R33

Since `warnInjectGlobalDeprecated` has no value in production mode, calling it causes the build to fail. Either it should check that it has a value, check the env. or noop. 

## Expected Behavior
No warning is thrown when `injectGlobal` gets used with `NODE_ENV=production`

## Actual Behavior
Build fails with 

```js
TypeError: warnInjectGlobalDeprecated is not a function
```

**Comment by probablyup** [comment]
Ugh sorry. The function wasn't guarded properly. Just pushed 3.4.8 which fixes it.
