### ISSUE TITLE
v3.2.4: Error: Cannot find module 'path/to/project/node_modules/styled-components/scripts/postinstall.js'

### ISSUE THREAD

**Issue by ApacheEx** [styled-components/styled-components#1651]
after upgrading styled-components from 3.2.3 to 3.2.4 I got this message:
![image](https://user-images.githubusercontent.com/1918108/38144054-e5a555a6-344b-11e8-9d04-aef2ae404640.png)

Node version: v8.11.0
Npm version: 5.8.0

**Comment by probablyup** [comment]
package.json “files” array phil, probably

**Comment by mxstbr** [comment]
@kitten mind undoing that release and trying anew? :wink:

**Comment by glenselle** [comment]
Looks like Phil went home for the weekend 😆

**Comment by kitten** [comment]
Fixed with 3.2.5. Sorry about that 😅

**Comment by webbhead777** [comment]
Thanks, @kitten! Enjoy you're weekend 🎉
