### ISSUE TITLE
React native 0.81 support

### ISSUE THREAD

**Issue by NikhilCodeblaze** [styled-components/styled-components#5610]
After upgrading RN from 0.74 to 0.81 , styled components give document undefined error , i add patch as per https://github.com/styled-components/styled-components/issues/5576#issuecomment-2816629148

but now getting [runtime not ready]: TypeError: undefined is not a function

<img width="1170" height="2532" alt="Image" src="https://github.com/user-attachments/assets/fd9472c3-dfdb-4387-b232-f210202ed84b" />

**Comment by mucahitbircan** [comment]
could u share your package.json file

**Comment by liam-grapeseed** [comment]
same issue. Please help

**Comment by quantizor** [comment]
Fixed — the root cause was that `flatten.ts` had value imports of `Keyframes` (for `instanceof`) and `StyleSheet` (for a parameter type), which transitively pulled the entire DOM sheet stack (`Sheet.ts` → `Tag.ts` → `dom.ts` → `Rehydration.ts`) into the native build. Newer RN/Hermes runtimes fail at module evaluation time when encountering `document` references.

The fix replaces `instanceof Keyframes` with a branded symbol check (`Symbol.for('sc-keyframes')`) and converts the imports to `import type`, which TypeScript strips at compile time. The native bundle drops from ~44KB to ~14KB with zero `document`/`window` references.

Will be in the next release.

**Comment by quantizor** [comment]
This fix is available in `styled-components@6.4.0-prerelease.0`. Please try it and report any issues:

```
npm install styled-components@6.4.0-prerelease.0
```
