### PR TITLE
chore: fix changeset package name and add test:types script

### PR DESCRIPTION
**Pull request by quantizor**
## Summary
- Fix changeset from #5654 to reference `styled-components` instead of `@xavescor/styled-component`
- Add `test:types` script with dedicated `tsconfig.test-types.json` that includes `src/test/types.tsx`—previously excluded from compilation and never validated
- Add `DefaultTheme` augmentation scoped to the test tsconfig so theme property references compile without casts
- Fix pre-existing broken `@ts-expect-error` directives (polymorphic type narrowing limitations)

## Why
The type test file was excluded from tsconfig via `"exclude": ["src/test"]`. A deliberate error (`const x: string = 12345`) passed silently—confirming the file was never checked.

### CODE REVIEW

**Comment by pedropedruzzi** [comment]
Amazing, thank you for the ref TS fix. Is there a new release planned for today or soon? Thanks.

**Comment by quantizor** [comment]
> Amazing, thank you for the ref TS fix. Is there a new release planned for today or soon? Thanks.

Yes you can try it with `styled-components@test`.

**Comment by pedropedruzzi** [comment]
So the ref TS fix was working well up until 6.4.0-prerelease.12. But it's broken in the final release and from 6.4.0-prerelease.13 beyound; I guess I might have broken after commit ab31e07.

Reproduceable code:

```
import styled from 'styled-components/native';
const StyledTextInput = styled.TextInput``;
const element = <StyledTextInput ref={ref => console.log(ref)}/>
```

Error:
```
src/components/Search/styles.tsx:23:34 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: Omit<FastOmit<FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }, "style"> & { ...; }): Element', gave the following error.
    Type '{ ref: (ref: any) => void; }' is not assignable to type 'IntrinsicAttributes & Omit<FastOmit<FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }, "style"> & { ...; }'.
      Property 'ref' does not exist on type 'IntrinsicAttributes & Omit<FastOmit<FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>>, keyof ExecutionProps> & FastOmit<...> & { ...; }, "style"> & { ...; }'.
  Overload 2 of 2, '(props: FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>> & { as?: NativeTarget | undefined; forwardedAs?: NativeTarget | undefined; }): ReactNode', gave the following error.
    Type '{ ref: (ref: any) => void; }' is not assignable to type 'IntrinsicAttributes & FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>> & { ...; }'.
      Property 'ref' does not exist on type 'IntrinsicAttributes & FastOmit<TextInputProps, never> & Partial<Pick<TextInputProps, never>> & { ...; }'.

23 const element = <StyledTextInput ref={ref => console.log(ref)}/>
                                    ~~~


src/components/Search/styles.tsx:23:39 - error TS7006: Parameter 'ref' implicitly has an 'any' type.

23 const element = <StyledTextInput ref={ref => console.log(ref)}/>
                                         ~~~
```
