### ISSUE TITLE
PROPS WORKING, BUT WITH TYPE ERROR

### ISSUE THREAD

**Issue by ViniDevBR** [styled-components/styled-components#4184]
Im using version 6.0.8

I have this component to use with React Native:
```js
import styled, { DefaultTheme } from 'styled-components/native'

interface TextProps {
  weight: keyof DefaultTheme['WEIGHT']
  color: keyof DefaultTheme['COLORS']
  size: number
}

export const Text = styled.Text<TextProps>`
  font-family: ${({ theme, weight }) => weight ? `Inter_${theme.WEIGHT[weight]}` : 'Inter_400'};
  color: ${({ theme, color }) => color ? theme.COLORS[color] : theme.COLORS.TEXT};
  font-size: ${({ size }) => size ? `${size}px` : '16px'};
`
```

But when i use the props color or weight or size... This works good, but with type error:
```js
No overload matches this call.
  Overload 1 of 2, '(props: TextProps | Readonly<TextProps>): Text', gave the following error.
    Type '{ children: string; color: string; size: number; weight: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
      Property 'color' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
  Overload 2 of 2, '(props: TextProps, context: any): Text', gave the following error.
    Type '{ children: string; color: string; size: number; weight: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.
      Property 'color' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Text> & Readonly<TextProps>'.ts(2769)
```

![image](https://github.com/styled-components/styled-components/assets/106121034/93bb5bb7-6440-42d3-a2bb-f7cd18e5e7a5)

# Using version 6.0.7 this works good with TS.

**Comment by davide-barbagallo** [comment]
I have the same problem

**Comment by minorbiglemon** [comment]
I also am seeing this same problem

**Comment by ramonxm** [comment]
same issue

**Comment by keshavkatwe** [comment]
same issue

**Comment by lenartpapez** [comment]
Same here. Really annoying.

**Comment by dereklance** [comment]
same here

**Comment by ademarsj** [comment]
Same here

**Comment by ademarsj** [comment]
Related to #4165

**Comment by Mr-Fullstack** [comment]
here the same problem I'm using ^6.0.8

**Comment by krudos** [comment]
try 6.1.0

**Comment by ademarsj** [comment]
Working on 6.1.0, thanks.

**Comment by JosephKorel** [comment]
Downgrading it to 6.1.1 did not work for me :/

**Comment by quantizor** [comment]
Seems to be fixed in more recent builds, please open a new issue with a sandbox reproduction if you run into it thanks!
