### ISSUE TITLE
Docs should reflect what works with react-native-web

### ISSUE THREAD

**Issue by tettoffensive** [styled-components/styled-components#3142]
## System:
 - OS: macOS 10.15.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
 - Memory: 491.99 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

I found a bunch of threads on this that are all archived, but my solution was different.

## Steps to reproduce

1. Clone https://github.com/zeit/next.js/tree/master/examples/with-react-native-web
2. Install styled-components

```js
import * as React from 'react'
import { Text, View } from 'react-native'
import styled from 'styled-components';

const Title = styled(Text)`
  font-size: 24px;
  color: tomato;
`;

export default function App(props) {
  return (
    <View>
      <Title accessibilityRole="header">
        React Native for Web & Next.js
      </Title>

      <Text accessibilityRole="link" href={`/alternate`}>
        A universal link
      </Text>

      <View>
        <Text accessibilityRole="header" aria-level="2">
          Subheader
        </Text>
      </View>
    </View>
  )
}
```

## Expected Behavior

Of course it would be nice to use the `styled.Text` syntax, but the main issue was that most discussions I found on this said to `import styled from 'styled-components/native`.

It wasn't until I decided to ignore that AND try it with another suggestion of using the `styled(Text)` syntax that I got it working.

## Actual Behavior

- `'styled-components'` AND  `styled.Text`:
`TypeError: Cannot read property 'withConfig' of undefined`
- `'styled-components/native'` AND  (`styled.Text` OR `styled(Text)`:
`Error: Cannot find module 'react-native'`
- `'styled-components'` AND  `styled(Text)`: **SUCCESS**

**Comment by tettoffensive** [comment]
https://github.com/necolas/react-native-web/issues/1618 `import styled from 'styled-components/native` now works with react-native-web 0.12 however, the owners of that project recommend not using styled-components because of the _"runtime cost with no benefits."_
