### ISSUE TITLE
v2 prerelease feedback

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#453]
If you're using the v2 pre-release, please let us know in a comment below if it works well for you! If you encounter bugs, **please submit individual issues for them**!

> To try the v2 prerelease, use `npm install styled-components@next babel-plugin-styled-components` and add the plugin to your Babel configuration like a regular Babel plugin. The plugin is optional as it only provides consistent naming for SSR as well as some pre-processing.

**Comment by garmjs** [comment]
Im not using v2 but just tested and i see if you use minify option it break parsing

I'm using 
 `node v7.0.0`
`webpack 2`
`styled-components@next` with `babel-plugin-styled-components`

## Steps to reproduce
```
const Box = styled.div`
  background-color: orange;
  width: 100px;
  height: 100px;
`
```

## Expected Behavior
```.app__Box-75m7jb {} .dwklpT {background-color: orange;width: 100px;height: 100px;}```

## Actual Behavior
```.app__Box-75m7jb {}.dwklpT {background-color: orange;width: 100px;height: 100px;}```

![kapture 2017-02-05 at 22 01 48](https://cloud.githubusercontent.com/assets/5017156/22629859/0f1eb9c8-ebef-11e6-87ac-5ab52d19c4bf.gif)

**Comment by svrcekmichal** [comment]
I've been using it little bit and wanted to do something like this:
```
const Button = styled.button`...`

const Block = styled.div`
&:hover > ${Button} {
   ...
}
`
```
but I was not able to make it work, so maybe there is issue between chair and computer :D . Component `displayName` works great to me and didn't found any bug now.

**Comment by axelson** [comment]
As I reported in #434 I'm successfully using v2 in a small internal project (that uses create-react-app). Didn't have to make any changes.

**Comment by three60five** [comment]
Do the changes in v2 around attr mean that using tachyons and styled-components together will be simplified?

**Comment by geelen** [comment]
@three60five yep! #365 is the PR that adds that.

**Comment by IljaDaderko** [comment]
Just tried `2.0.0-3` in a `react-native@0.41.2` project, seems to be working like before, without changing anything.

**Comment by adjnor** [comment]
When I try using babel-plugin-styled-components, I get this error in the console:
`__WEBPACK_IMPORTED_MODULE_3_styled_components__.default.a.withConfig is not a function at eval ...`
The component giving the error being defined as so:
```
const MyComponent = styled.a`{
// styles here
}`;
```
I'm using styled-components v2.0.0-4 and babel-plugin-styled-components v1.0.0

**Comment by garmjs** [comment]
@adjnor `styled-components` is using tag functions [Computing tag functions for ES6 template literals](http://www.2ality.com/2016/11/computing-tag-functions.html)

remove bracket
```
const MyComponent = styled.a`
// styles here
`;
```

**Comment by adjnor** [comment]
@garmjs Thanks, that fixed it! I still think the error I got is a bug though, the brackets inside the tagged literal is valid syntax as far as I know, otherwise how would styled-components work? With that said, I was using the brackets because of a quirk with atom which wasn't properly highlighting the css code without the brackets but now it's fine.

**Comment by mxstbr** [comment]
> the tagged literal is valid syntax as far as I know, otherwise how would styled-components work?

Nope, you don't need brackets at all. See any example in the docs 😊

**Comment by kopax** [comment]
I am trying to install __styled-components/babel-plugin-styled-components__ with webpack (react-boilerplate).

I have added in my _internals/webpack/webpack.dist.babel.js_

```jsx
{
  "plugins": ["styled-components"]
}
```

```bash
> cross-env NODE_ENV=production webpack --config $(pwd)/internals/webpack/webpack.dist.babel.js --color -p --progress

/bootstrap-styled/node_modules/webpack/bin/webpack.js:315
                throw e;
                ^

TypeError: arguments[i].apply is not a function
```

**Comment by thysultan** [comment]
@kopax #1 & #2 might be because stylis removes all comments(line, block) and #3 the css syntax shouldn't be different, can you post an example of some css that is processed incorrectly.

**Comment by kopax** [comment]
@thysultan #1 and #2, the appended css that appear in the `<style>` tag doesn't have any comment.

But my module using styled-components made with webpack is compressed in a .js file. In this file I can still see many comments and the filesize is 416kb instead of 422kb. So this appear not to work!

This is a component that doesn't work with styled 2.0 : 

https://gist.github.com/kopax/597f0801ab3e87ba1adfe6b72ef77967

Style tag generated css : http://pastebin.com/87KzCi0Q

And this is the one corrected (added semicolon to every last css rules)

https://gist.github.com/kopax/d2672ceb7121d820de5f1e7cd7c49457

Style tag generated css : http://pastebin.com/nMmUCGVB

**Comment by thysultan** [comment]
@kopax Does the second one(with semicolons) also not work?

**Comment by kopax** [comment]
@thysultan I have updated mine, It was still missing semicolon at the beggining (3).

It work afterthat, but I am currently correcting all the components that are not using semicolon for last rules, they are all broken.

**Comment by thysultan** [comment]
@kopax It actually should work without semicolon(the last property) since that is valid css, i'll look into this.

**Comment by kopax** [comment]
Thank you @thysultan , do you have an idea for the deprecation warning and all the other points ?
I am very surprised that there is no error handling.

**Comment by thysultan** [comment]
.6 & .7, it's a bug in stylis, i've patched it in v1.1.12, thanks for finding this. The other points i don't know.

**Comment by kopax** [comment]
How can I get the patched version ? I am correcting everything by hand.

**Comment by thysultan** [comment]
@kopax re-install, i think npm should pull the latest version patch of stylis.

**Comment by kopax** [comment]
Which version? I have fixed in my package.json : 

    "babel-plugin-styled-components": "1.0.0",
    "styled-components": "2.0.0-4",

This may sound a little dumb but how did you patch your `package.json` without releasing anything ?

**Comment by k15a** [comment]
`rm -rf node_modules && npm install` but this might not work if you're using webpack@2

**Comment by kopax** [comment]
I am using  `"webpack": "2.2.0"`. How is this webpack related?

**Comment by k15a** [comment]
Because Webpack will use the bundled version of styled-components if configured correctly which is not updated currently.

**Comment by kopax** [comment]
I am not aware of this, would you mind share a link where I can read ? Using webpack 2.0, we will have to wait for the next official npm release right ? But it's also possible to install from a github directly, for that, I need to see your commit.

**Comment by k15a** [comment]
Webpack checks for the fields [`browser, module, main`](https://webpack.js.org/configuration/resolve/#resolve-mainfields) in your package.json (in this case styled-components one) for the file it will take as the module entry. In the case of styled-components it will take the [`"module": "dist/styled-components.es.js"`](https://github.com/styled-components/styled-components/blob/master/package.json#L8) line which directs to a bundled version (with all dependencies except React). This is currently a problem because you will only get the version of the dependencies which were released as styled-components got last released, which might be some outdated one.

**Comment by kopax** [comment]
I wonder if I install stylis myself as a dependency of the project if my dependency will be prioritized than the one from styled. I will wait for the next release of styled-components. I manage to restore my project by correcting every missing semicolon and correcting every comment that were using apostrophe. Thanks for all the explanation.

**Comment by thysultan** [comment]
@kopax 

> correcting every comment that were using apostrophe

Was this causing problems, can you share an example?

**Comment by kopax** [comment]
@thysultan yes I was having issues in components that had semicolon to each css rules. I manage to generate the css by removing `'` in comments from that file. I don't have any example to share but if it again, I'll share the example.

**Comment by santaclauze** [comment]
Hey, been testing v.2. It's up and running.

I have encountered similar issues to the discussion above. Semicolons are the worst I reckon.

I wanted to know if some css is not acceptable anymore. Prior to v.2, the following css worked:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-deck {
          display: flex;
          flex-flow: row wrap;
        
          .card {
            display: flex;
            flex: 1 0 0;
            flex-direction: column;  
            &:not(:first-child) { margin-left: ${props.theme['$card-deck-margin']}; }
            &:not(:last-child) { margin-right: ${props.theme['$card-deck-margin']}; }
          }
        }
      `
    )}
```

But since v.2 it crashes. After debugging, I realized that the following lines made the css crash:
```css
&:not(:first-child) { margin-left: ${props.theme['$card-deck-margin']}; }
&:not(:last-child) { margin-right: ${props.theme['$card-deck-margin']}; }
```

If I delete one of them, it works fine, but for some reason, when both are applied, they make the css injection crash. 

Also, this works:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-group {
          display: flex;
          flex-flow: row wrap;
      
          .card {
            flex: 1 0 0;
      
            + .card {
              margin-left: 0;
              border-left: 0;
            }
      
            ${ifThen(props.theme['$enable-rounded'],
              `                
                  background-color: red;
                
              `
            )}  
          }
        }
      `
    )}
```

But not:

```css
${mediaBreakpointUp(
      'sm',
      props.theme['$grid-breakpoints'],
      `
        &.card-group {
          display: flex;
          flex-flow: row wrap;
      
          .card {
            flex: 1 0 0;
      
            + .card {
              margin-left: 0;
              border-left: 0;
            }
      
            ${ifThen(props.theme['$enable-rounded'],
              `     
                  .car-img-bottom {    
                      background-color: red;
                  }
              `
            )}  
          }
        }
      `
    )}
```

These behavios are quite bizarre. I am not sure if they come from a bug here, or due to another small issue like 'semicolons' who have been a bit of a hassle for me.

**Comment by mqklin** [comment]
Just finished migrating from `react-css-modules + postcss` (38 `.sss` files, 1658 lines of `sss` code) to this exciting project. The only problem I have - I can't use `& ~ &`, because guess what... I use `webpack 2` =/  Guys, please, make a release.

**Comment by thysultan** [comment]
@santaclauze are you also using webpack 2?

**Comment by santaclauze** [comment]
@thysultan yeap.

**Comment by santaclauze** [comment]
Got an example up of the bug so you can see more clearly how the css is breaking (I should have been clearer in my last post -_-):

http://www.webpackbin.com/4J0u-y_Ff

As you see in the example above,``` CardDeckOk``` will display its css correctly, but in the second case, ``` CardDeckNok ``` it will crash. 

It seems to be coming from the media queries.

**Comment by thysultan** [comment]
@santaclauze Thanks for finding this, will push a patch.

**Comment by kopax** [comment]
Thanks for the hard work. So far I have listed the following issues : 

1. line comment in css `/**/` are still present in distribution build
1. last semicolon brake css rendering.
1. media query can randomly brake css.

Our solution was to revert to `v1.4.3`, for when is the next release ?

**Comment by thysultan** [comment]
@kopax @santaclauze The media query bug was patched upstream stylis, should be resolved once a new v2 release is out.

**Comment by mxstbr** [comment]
Pushing a new release of styled-components with an updated stylis version now!

**Comment by mxstbr** [comment]
New release with stylis update is out as `2.0.0-5`! `npm install --save styled-components@next` and you should get it :tada:

**Comment by kopax** [comment]
Thanks, I am testing it right now and it seems all good. I still have these pending questions: 

1. Will the CSS rules be validated (existing rules must be applied) ?
1. Will you add the ability to generated parsing errors (missing `}`, missing `;`} ?
1. Will the generated css generate warning and error if syntax is wrong ?
1. More generally what will be the adopted strategy for errors in `styled-components` /`stylis` ? (so  it's completely ignored)

We use intellij and the color integration doesn't look so good, we spend times seeing our mistake so this is kind of important things to know for the futur.

**Comment by mqklin** [comment]
@kopax I use this code: `margin-bottom: ${props => props.MB && '10px'}`, so when MB is not passed, I get this: 
![margin-bottom-sc](https://cloud.githubusercontent.com/assets/9456433/23493733/c72e9bc0-ff2f-11e6-9aa1-a724c480a77d.png)
And it's very nice, because I don't have to always append default styles. So I hope wrong-syntax-warnings will be pluggable.

**Comment by thysultan** [comment]
@kopax On the side of stylis there one more small piece missing to allow creating a linter plugin that should be added in v1.2

**Comment by kopax** [comment]
@thysultan that's nice, for when is scheduled stylis `v1.2` ? 

Also, in `v1.4.3`, it was impossible to render the stylesheet using javascript, we have to check the import in `<html>` and see how it look like.

Is there now a way in styled-components `2.0.0-5` to render the css using javascript ?

**Comment by k15a** [comment]
@kopax if you mean `injectGlobal` it's not getting removed as far as I know.

**Comment by kopax** [comment]
@k15a , I don't mean `injectGlobal`.

I mean the rendered css injected in the page when a component render is not accessible through javascript.

Something like that would be nice.

```jsx
const StyledDiv = styled.div`
  border: 1px solid red;
  &:hover {
    border: 1px solid blue;
  }
`
console.log(StyledDiv.getStyleSheet()); ==> valid css
```

As far as I know, @mxstbr confirmed it was not possible with v1 of styled-components, but maybe it will be possible using stylis ?

I have opened a new Issue #549 regarding `v2.0.0-5`, it is not possible to use anchor link and `<ThemeProvider />` anymore.

**Comment by mxstbr** [comment]
Published `2.0.0-6`! I haven't had time to look into #549 yet, will do so after I get back home next week.

**Comment by jgoux** [comment]
@svrcekmichal Whaaat? Is it possible to compose styles that way in v2? If so, it's **awesome**!

**Comment by k15a** [comment]
@jgoux if you mean this:
```JS
const Button = styled.button`...`

const Block = styled.div`
&:hover > ${Button} {
   ...
}
`
```
Yes that's possible with v2 of styled-components.

**Comment by jgoux** [comment]
@k15a 
![image](https://cloud.githubusercontent.com/assets/1443499/23673918/54742cb4-0374-11e7-9256-82896b336dcd.png)

**Comment by kopax** [comment]
just reported a new bug in `2.0.0-7` https://github.com/styled-components/styled-components/issues/569

**Comment by santaclauze** [comment]
I have managed to fix the issue but I am not certain on how to behave for my future code.

# Version

styled-components 2.0.0-7
reactstrap 4.2.0

# Steps to reproduce

I have created 3 cases:

1. __A__: Component created with `styled.button`
1. __B__: Component created with `class Button2 extends React.Component {}` with external _[default] props_
1. __C__: Component created with `class Button3 extends React.Component {}` with internal _static [default] props_

Case B use [the official recommended syntax for writing props](https://facebook.github.io/react/docs/typechecking-with-proptypes.html#default-prop-values)

Case C use `static` keyword within the class from [the proposition of babel](http://babeljs.io/blog/2015/06/07/react-on-es6-plus#property-initializers), __Webpackbin does not support the `static` keyword so I couldn't reproduce it in the bin__.
Copy Paste example and uncomment lines 11 and 13.

- In case A: within styles
- In case B and C: within render and within styles

https://www.webpackbin.com/bins/-Kf5Tdg7bfj2oWZzIb1V

Problematic Case:
```jsx
const defaultProps = {
  theme: themeBs,
};

class ButtonClass extends React.Component {
...
}

ButtonClass.defaultProps = defaultProps;
export default ButtonClass;
```

Fixed Case (Case C):

```jsx
const defaultProps = {
  theme: themeBs,
};

class ButtonBetter extends React.Component {
  static defaultProps = defaultProps;
...
}

export default ButtonBetter;
```

Moving the defaultProps inside the component using static keyword solve the issue.

# Expected Behavior

Custom theme to be applied

# Actual Behavior

Default theme is applied

# Questions

1. Is there any way to use ` static` keyword in Webpackbin? Or is there any work around to produce an equivalent results? In other words, what does the static keyword exactly do and how to reproduce it without him?

1. It seems the class doesn't contain publicly  `Component.defaultProps` or `Component.staticProps` anymore. Should we support the react way or the babel way ? 

1. What will happen to stateless components and styled if we are obliged to define `defaultProps` within the component? (As it seems that you cannot define static in non class component (`styled.button`, stateless components, ...))

**Comment by GGAlanSmithee** [comment]
> is there any work around to produce an equivalent results? In other words, what does the static keyword exactly do and how to reproduce it without him?

```javascript
class ButtonBetter extends React.Component {
  static defaultProps = defaultProps;
  ...
}
```

```javascript
class ButtonBetter extends React.Component {
...
}

ButtonBetter.defaultProps = defaultProps
```

The `static` keyword puts the property / method on the class itself rather than on an instance of the class.

**Comment by santaclauze** [comment]
Unfortunately It's not completely true:

Try to write this : 

```jsx
class ButtonBetter extends React.Component {
  static defaultProps = defaultProps;
  ...
}

console.log(ButtonBetter.defaultProps);
```

will behave differently than 

```jsx
class ButtonBetter extends React.Component {
...
}

ButtonBetter.defaultProps = defaultProps
```

As a result, using keyword static also repair the user theme that is toggling to default when state change.

**Comment by GGAlanSmithee** [comment]
@santaclauze oh, really, I must missunderstand something than. Care to elaborate. Looks like it's generating the same code [in this babel example](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=class%20A%20%7B%0A%09static%20a%20%3D%20'hi'%0A%7D%0A%0Aconsole.log(A.a)%0A%0Aclass%20B%20%7B%0A%7D%0A%0AB.b%20%3D%20'hi'%0A%0Aconsole.log(B.b))

**Comment by santaclauze** [comment]
My mistake, It's not related to `static keyword`, thanks for pointing this out.

I have checked my dist file and I've notice these differences in my builds: 

With static:

```js
Button.defaultProps = {
  theme: _theme2.default,
  tag: 'button',
  color: 'secondary'
};
Button = (0, _styledComponents2.default)(Button).withConfig({
  displayName: 'Button__Button',
  componentId: 'Button__Button-hfs9jv'
})(['', ' '], function (props) {
  return ...
});

exports.default = Button;
```

Without static:

```js

Button = (0, _styledComponents2.default)(Button).withConfig({
  displayName: 'Button__Button',
  componentId: 'Button__Button-hfs9jv'
})(['', ' '], function (props) {
  return ...
});

Button.defaultProps = defaultProps;

exports.default = Button;
```

I have followed the way recommended [in the styled-components documentation](https://github.com/styled-components/styled-components#defaults) 
They recommend to add your defaultProps after we have applied the styles with styled. 

This will result in this bug.

- Is the styled-components documentation still up to date ? 
- Should we wait for a fix or a doc update ?
- Can't we just add the defaultProps in the class ?
- How do we do for the components created with `styled.button` ? These can't be corrected this way.

**Comment by dmitrizzle** [comment]
V2 works wonderfully for me, but then my app is still in its infancy. Thank you everyone who wrote this and submitted PRs.

Two questions:

1. I've heard that random style names will be prefixed by component name, is that still happening?
1. Is there a shorter/better way to reference themed values? It's really messy for me, especially when I do something like this:
`left: calc(50% - ${ props => props.theme.size.font.make.larger - (props.theme.size.block.spacing / 2) }em);`

**Comment by reznord** [comment]
@dmitrizzle does composition work for you? 

```
const Button = styled.button`...`

const Block = styled.div`
&:hover > ${Button} {
   ...
}
`
```

I tried playing with it. But this wasn't working for me in v2.

**Comment by dmitrizzle** [comment]
@reznord youp, composition it works for me.

**Comment by kopax** [comment]
@mxstbr any update on the `<ThemeProvider />` issue ? 
I've tested the fix of @santaclauze but as he said, it is not possible to apply the defaultProps if it's a component created with `styled[element]`color: red;`

I thought v2 was for early 2017 but it look a bit too early. If we need a stable version within the next month should we just revert to v1? v2 components use a slightly different API ( `:global`) but it is still doable.

**Comment by romellogood** [comment]
@mxstbr when do you think v2 will be released? I've read somewhere you were shooting for Jan or Feb of this year originally.

**Comment by kopax** [comment]
Is this supposed to work in V2 ? because it is not re-rendering the `:global` part.

```jsx
const ifThen = (isOpen, rules) => {
  return isOpen ? rules : '';
}
styled.div`
    :global(body) {
      ${ifThen(props.isOpen, `margin-right: ${props.size}px !important;`)}
    }

    ${ifThen(!props.isOpen, `transform: translate3d(${props.size-10}px, 0, 0);`)}
`
```

**Comment by mqklin** [comment]
Maybe will be interesting for someone. https://ins.remontista.ru - css built with `styled-components` v2 and `raw-loader` only.

**Comment by drKnoxy** [comment]
Man the styled-components lib (raw from visualizer) dropped from 146k to 65k for me, which resulted in my vendor bundle (min,gz) dropping from 140k to 116k. Cheers!

**Comment by kopax** [comment]
#612 Is it stylis or styled issue ? @thysultan

**Comment by kopax** [comment]
Any update on this ?

**Comment by Thr44** [comment]
I updated to styled-components^2.0.0-17 in order to use jest snapshots with jsdom + enzyme mount, however, when I call :
`toMatchStyledComponentsSnapshot()` I get:

`TypeError: styleSheet.rules is not a function`

here's a complete test that is failing:

`
import React from 'react';
import renderer from 'react-test-renderer';
import styled from 'styled-components';

describe('styled Component Tests', () => {

  it('should render a styled h4', () => {
    const iconStyles = `
      margin-left: -2px;
      margin-right: 4px;
      margin-top: -3px;
    `;

    const H4 = styled.h4`${iconStyles}`;

    const container = renderer.create(
      <H4>"a label"</H4>
    ).toJSON();
    expect(container).toMatchStyledComponentsSnapshot();
  });`

**Comment by philpl** [comment]
@Thr44 We have a new StyleSheet and SSR API in the RC releases, so you'll have to update your SSR code :/

**Comment by Thr44** [comment]
@philpl thanks for the quick reply, do you have a link with an example I can follow up?

**Comment by philpl** [comment]
@Thr44 Actually I just realised that it's a problem with `jest-styled-components` itself. We'll need to file an issue there :/

**Comment by Thr44** [comment]
Thanks @philpl, 

you're right. if I remove jest-styled-components it works fine, although its useless due to the generated classNames.

There's an open issue for styled-components v2, so I left a comment to follow-up there:
https://github.com/styled-components/jest-styled-components/issues/5

**Comment by wmertens** [comment]
@philpl When I try to use the `StyleSheetManager` approach, it breaks:

```
Warning: Failed prop type: Invalid prop `sheet` of type `ServerStyleSheet` supplied to `StyleSheetManager`, expected instance of `StyleSheet`.
    in StyleSheetManager (at middleware.js:49)
!!! Could not prerender, please fix this !!! { TypeError: styleSheet.getName is not a function
    at ComponentStyle.generateAndInjectStyles (/myproj/node_modules/styled-components/lib/models/ComponentStyle.js:53:37)
    at StyledComponent.generateAndInjectStyles (/myproj/node_modules/styled-components/lib/models/StyledComponent.js:117:38)
    at /myproj/node_modules/styled-components/lib/models/StyledComponent.js:141:43
    at subscribe (/myproj/node_modules/styled-components/lib/utils/create-broadcast.js:31:7)
    at StyledComponent.componentWillMount (/myproj/node_modules/styled-components/lib/models/StyledComponent.js:132:28)
    at walkTree (/myproj/node_modules/react-apollo/src/server.ts:59:18)
```

`sheet.collectStyles(<YourApp />)` works fine though.

**Comment by philpl** [comment]
@wmertens I made a mistake in the docs it seems. You'll need to pass `sheet.instance` into that prop ;)

**Comment by wmertens** [comment]
Indeed, things work nicely now! (apart from the preprocess issue I created for the babel plugin)

**Comment by kopax** [comment]
Can we have some news about v2 ?
I want to know what are the blocking issues for deploying in production.
What are the compatible browsers ? I see an issue saying IE10 is not working. Anyone has information about this ? I am using `v2.0.0-17`

**Comment by sergop321** [comment]
@philpl Could you please update the new docs https://www.styled-components.com/docs/advanced#server-side-rendering  with  sheet.instance instead of sheet

**Comment by mxstbr** [comment]
Since v2 is now out (:tada:), I'll close this issue. Thanks for the feedback everybody, I hope you enjoy this release! (read more about the changes: https://medium.com/styled-components/announcing-v2-f01ef3766ac2)
