### ISSUE TITLE
[Typescript] css mixin - problem with theme

### ISSUE THREAD

**Issue by lluzak** [styled-components/styled-components#1821]
After updating to styled-components 3.3.3, i'm getting errors in all components which use mixins.

## Reproduction
 
https://codesandbox.io/s/m7lqkkw6l8

## Expected Behavior

Should not require ```theme``` prop.

## Actual Behavior

```
Property 'theme' is missing in type '{ children: string[]; }'.
```

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by kachkaev** [comment]
Looks like I have a similar issue in 3.3.3:

```ts
const Statement = styled.div`
  margin: 0 auto;
  padding: 0 ${(p) => p.theme.gutter}px;
`;
```

> [ts] Property 'theme' does not exist on type 'never'.

Could be related to https://github.com/styled-components/styled-components/pull/1798

**Comment by Igorbek** [comment]
@kachkaev the second case I could not reproduce. This works with TS 2.9.1:

```tsx
const Case2 = styled.div`
    ${props => props.theme.gutter}px
`;
<Case2 />; // ok
```

also, the other case reported in #1798, works too

```tsx
const Case3Inner = (p: {flag?: boolean}) => <div />;

const Case3 = styled(Case3Inner)`
  background: ${p => p.flag ? "red" : "white" };
`;

<Case3 />; // ok
```

**Comment by probablyup** [comment]
@Igorbek ok based on this and the other typing related PRs that have been merged, is this something we can tackle without requiring TS 2.9? I have it on the v3.4 roadmap list.

**Comment by probablyup** [comment]
Alright, let's table this then and make a master issue on DT with the unsolved problems so they can be solved there.

**Comment by probablyup** [comment]
Thank you so much for your efforts on this by the way!

**Comment by Igorbek** [comment]
Thank you. I would love to put more time in that but have been quite busy recently, as I may have noticed with response/review delays.

**Comment by timm-aym** [comment]
I see the same issue as @kachkaev when upgrading to 3.3.3.

We're using the `styledComponents as ThemedStyledComponentsModule<typeof theme>` export, and now every component of type `styled.X` requires the `theme` property to be set (as per the TypeScript definition).

This is not desired, as we're using the theme provider.

Switching it to `styled.X<{}>` fixes the type issue, though I would rather not update all custom component declarations.

Is there any other known workaround for this / a plan to revert this? (3.3.2 was fine)

**Comment by probablyup** [comment]
@Igorbek what do you think is better here? Revert or leave as-is. I'm leaning towards reverting.

**Comment by Igorbek** [comment]
Let me compare what was introduced in 3.3.3 and why did it break this.

**Comment by Igorbek** [comment]
I created a PR that reverts the change introduced in 3.3.3.
